# Stage 1: Application Build
FROM node:16-alpine as build-step

WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:prod

# Stage 2: Setting up NGINX to Serve the Application
FROM nginx:1.22.0-alpine
ARG APP_NAME
# Copying the built application from the build stage
COPY --from=build-step /app/dist/${APP_NAME}/browser/ /usr/share/nginx/html

COPY nginx.default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
