FROM node:lts-alpine
WORKDIR /app
RUN npm install -g nx@latest

COPY package*.json ./
RUN npm ci
COPY . .

COPY ["docker-entrypoint.test.sh", "/usr/local/bin/"]
RUN chmod +x /usr/local/bin/docker-entrypoint.test.sh
ENTRYPOINT ["docker-entrypoint.test.sh"]
