#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --cached --quiet -- neox-api/; then
  exit 0
else
  cd neox-api && npm run check:lint-all
 if [ $? -ne 0 ]; then
   echo "Backend linting failed"
   exit 1
 fi
